version: '3.8'
services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: https://integrating-newark-pale-provisions.trycloudflare.com
    container_name: recruitment_frontend
    restart: always
    ports:
      - "3001:3000"

  frontend_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: recruitment_frontend_tunnel
    command: tunnel --url http://frontend:3000
    restart: always
    depends_on:
      - frontend
